### ISSUE TITLE
How were the reward hyperparameters obtained?

### ISSUE THREAD

**Issue by ManifoldFR** [facebookresearch/ScaDiver#5]
Hi,

I read the paper and looked through the code. I am wondering how the parameters (lengthscales, for instance) for the reward kernels and the reward tree were obtained. Was it some rule of thumb?
I guess random search or using optuna is a possibility, but that would be expensive, right?

Thanks.

**Comment by Jungdam** [comment]
Hi,

In case of some reference values are available (e.g., similar terms in Peng 2018 or Park 2019), I first adopted the values in those references then modified them accordingly. Otherwise, I choose parameters experimentally from scratch, where my rule of thumb is to make all the terms be equal as possible then modify the values according to the achieved results.

**Comment by ManifoldFR** [comment]
Thanks !
